# This file is managed by `repo_helper`. Don't edit it directly
---

language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:

  - pip install pip  --upgrade
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi
  - deploy_conda


jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/enum_tools
        provider: pypi
        user: "DomDF"
        password:
          secure: ccXgmg5Goemg2IFrw1F62mtnVmVVPpEVPCrPhAfuW4uEh9MgfluULgFjOZUaur9frgTwlFuXjv7Uyz66+IBH4m+W8z6vKaBq260fi+6Dues+BgyOvVvDmPm1+pE7rVxSWzDJgfEiRJjGo0CjrVmqvFIyamwJqojkR3AcNRtRZFFaH0P5gA1EcAQrfngn4IK6lxgYd0b6CrwZodyr/o7xDMpqikKcYJAiXLtQp7CFeo/NfRWIgzfhvquxpA81AZbeyVL4cciDLsmQHqib6yhHb8sGDGCo9tCUB0oWf7tFbS/diIFYqumqbdumxTl8p7u4NL7XJc6F8ySTQ0RsHk1/3U7z5hSGQDbhAsGdsBeEf4iM22M1CqJ8raFcZXaeF2DLqFdTHovsG0BNG5VWNsrgn2G+S60wPgiQQBZKtNrvIOVu1QGCCUdBUO1cpnrIk4g8ZB7P12uHDWVWUDF1xYhji/F1JEIZ1eVgmVWPKBbGe+n6WfQIxfRPy++xyNU2F0C4UnapkR894UW8LDfAFS1K5cZluco8ZYj0AQgR5mdQkCCfcWCIgabtTyrsPum2sFFFbQyWJ7ZEfUPX7cfu5qKJ4TmOFZGTEp7ii+jYhaSGfpsayV4wxIJD55n0RhsxcNk908dXKn78AWBVVjHqdfWKnCKF0Lc26G0g9OoNeRp74II=
        distributions: "sdist bdist_wheel"
        skip_existing: true
    - stage: deploy_conda
      python: "3.6"
      addons:
        apt:
          update: true
      install:
        - pip install rst2txt yolk3k
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - chmod +x .ci/travis_deploy_conda.sh
      script: skip
      deploy:
        on:
          repo: domdfcoding/enum_tools
        provider: script
        script: .ci/travis_deploy_conda.sh || return 1;
